#!/bin/bash

echo "----------------------------------------------------------------"
echo "  PRIME PICKLEBALL SETUP CHECK"
echo "----------------------------------------------------------------"
echo ""
echo "1. DATABASE MIGRATION (Required)"
echo "   You must run the SQL script in your Supabase Dashboard."
echo "   - Go to: https://supabase.com/dashboard/project/_/sql"
echo "   - Click 'New Query'"
echo "   - Copy the contents of: src/server/fix_rls.sql"
echo "   - Click 'Run'"
echo ""
echo "2. VERIFY FIX (Optional)"
echo "   Run this command in your terminal to verify the database:"
echo "   npx tsx src/server/verify-fix.ts"
echo ""
echo "3. RESTART SERVER"
echo "   After applying the SQL, restart your server to pick up changes."
echo "----------------------------------------------------------------"
